const uuid = require('uuid');

const data = [
    {
        idJugador: uuid.v4(),
        nombre: 'Juan Soriano',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886830/Jugadores/Leganes/soriano_g1iikt.png',
        posicion: 'Portero',
        valor: '1.200.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Marko Dmitrovic',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886830/Jugadores/Leganes/dimitro_jk1qqm.png',
        posicion: 'Portero',
        valor: '800.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Sergio González',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886830/Jugadores/Leganes/sergiogon_uisez8.png',
        posicion: 'Defensa',
        valor: '1.500.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Jorge Sáenz',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886830/Jugadores/Leganes/saenz_ofy6hj.png',
        posicion: 'Defensa',
        valor: '1.200.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Matija Nastasić',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886830/Jugadores/Leganes/nastasic_c5um44.png',
        posicion: 'Defensa',
        valor: '1.000.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Javi Hernández',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886829/Jugadores/Leganes/javihdz_jpnbyn.png',
        posicion: 'Defensa',
        valor: '2.000.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Enric Franquesa',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886829/Jugadores/Leganes/franquesa_mdyu8k.png',
        posicion: 'Defensa',
        valor: '1.500.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Borna Barišić',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886829/Jugadores/Leganes/barisic_zvg8o8.png',
        posicion: 'Defensa',
        valor: '1.000.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Valentin Rosier',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886829/Jugadores/Leganes/rosier_ajaiyu.png',
        posicion: 'Defensa',
        valor: '3.000.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Adrià Altimira',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886829/Jugadores/Leganes/alti_irvein.png',
        posicion: 'Defensa',
        valor: '1.500.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Renato Tapia',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886832/Jugadores/Leganes/tapia_tjp1tl.png',
        posicion: 'Mediocampista',
        valor: '3.500.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Yvan Neyou',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886831/Jugadores/Leganes/neyou_h4pufi.png',
        posicion: 'Mediocampista',
        valor: '2.500.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Julián Chicco',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886829/Jugadores/Leganes/chicco_kt0pf1.png',
        posicion: 'Mediocampista',
        valor: '600.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Seydouba Cissé',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886829/Jugadores/Leganes/cisse_ca069v.png',
        posicion: 'Mediocampista',
        valor: '3.000.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Darko Brašanac',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886830/Jugadores/Leganes/brasanac_dtc6os.png',
        posicion: 'Mediocampista',
        valor: '600.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Óscar Rodríguez',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886829/Jugadores/Leganes/oscar_lrksbb.png',
        posicion: 'Mediocampista',
        valor: '2.000.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Roberto López',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886829/Jugadores/Leganes/roberto_m2mqtt.png',
        posicion: 'Mediocampista',
        valor: '1.500.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Juan Cruz',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886828/Jugadores/Leganes/cruz_vwimhx.png',
        posicion: 'Delantero',
        valor: '4.000.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Duk',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886831/Jugadores/Leganes/duk_dm47ao.png',
        posicion: 'Delantero',
        valor: '1.200.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Dani Raba',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886828/Jugadores/Leganes/daniraba_rlcvxz.png',
        posicion: 'Delantero',
        valor: '1.800.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Munir El Haddadi',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886831/Jugadores/Leganes/munir_neinho.png',
        posicion: 'Delantero',
        valor: '1.500.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Miguel de la Fuente',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886831/Jugadores/Leganes/miguel_mov5wh.png',
        posicion: 'Delantero',
        valor: '2.000.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
    {
        idJugador: uuid.v4(),
        nombre: 'Diego García',
        foto: 'https://res.cloudinary.com/daskrmb6s/image/upload/v1743886831/Jugadores/Leganes/diegogar_qbbwlw.png',
        posicion: 'Delantero',
        valor: '1.500.000 €',
        puntuacion: 0,
        estado: 'Disponible',
        propietario: 'Ninguno',
    },
];

exports.data = data;
